import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link').filter({ hasText: 'Company' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('relearnsolutions-2');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('button', { name: 'Edit' }).first().click();
  await page.getByRole('tab', { name: 'Department' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('engineer');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('tab', { name: 'Position' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('engineer position');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('tab', { name: 'Employee' }).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('employee_relearn@relearnsolution.co.th');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone' }).press('Tab');
  await page.getByRole('textbox', { name: 'First name' }).fill('employee');
  await page.getByRole('textbox', { name: 'First name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last name' }).fill('A');
  await page.getByRole('textbox', { name: 'Last name' }).press('Tab');
  await page.getByLabel('Position*').selectOption('_6wBf');
  await page.getByLabel('Department*').selectOption('gi4PB');
  await page.getByLabel('Preferred Locale*').selectOption('EN');
  await page.getByRole('button', { name: 'Create Employee' }).click();
});